name: Deploy

on:
  workflow_dispatch:
    inputs:
      ref_name:
        description: "Branch or tag"
        required: true
        type: string

  workflow_call:
    inputs:
      ref_name:
        required: true
        type: string


concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Fetch Sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Build Rust Binaries
        uses: ./.github/actions/build-rust

      - name: Copy Faucet Backend
        run: |
          mkdir -p dist/docker
          cp target/release/faucet-backend dist/docker/faucet-backend

      - name: Build Docker Image
        uses: ./.github/actions/build-docker
        with:
          ref_name: ${{ github.head_ref || github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run deployment wf
        env:
          RUN_NAME: ${{ format('Deploy {0} / {1} / {2}', vars.APP_NAME, needs.build.outputs.component || '-', needs.build.outputs.image_tag) }}
        uses: the-actions-org/workflow-dispatch@v4
        with:
          run-name: ${{ env.RUN_NAME }}
          workflow: deploy-v2.yml
          ref: main
          repo: ${{ vars.DEPLOY_REPO }}
          token: ${{ secrets.DEPLOY_REPO_TOKEN }}
          inputs: |
            {
              "app_name": "${{ vars.APP_NAME }}",
              "image_tag": "${{ needs.build.outputs.image_tag }}",
              "image_digest": "${{ needs.build.outputs.image_digest }}",
              "image_revision": "${{ needs.build.outputs.image_revision || github.sha }}",
              "run_name": "${{ env.RUN_NAME }}"
            }
