name: Deploy build

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      ref_name:
        description: "Branch or tag"
        required: true
        type: string

  workflow_call:
    inputs:
      ref_name:
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    permissions:
      packages: write
      contents: read
    with:
      ref_name: ${{ inputs.ref_name || github.ref_name }}

# disabled until moved to appropriate org (ton-blockchain or ton-org)
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Run deployment wf
#        env:
#          RUN_NAME: ${{ format('Deploy {0} / {1} / {2}', vars.APP_NAME, needs.build.outputs.component || '-', needs.build.outputs.image_tag) }}
#        uses: the-actions-org/workflow-dispatch@v4
#        with:
#          run-name: ${{ env.RUN_NAME }}
#          workflow: deploy-v2.yml
#          ref: main
#          repo: ${{ vars.DEPLOY_REPO }}
#          token: ${{ secrets.DEPLOY_REPO_TOKEN }}
#          inputs: |
#            {
#              "app_name": "${{ vars.APP_NAME }}",
#              "image_tag": "${{ needs.build.outputs.image_tag }}",
#              "image_digest": "${{ needs.build.outputs.image_digest }}",
#              "image_revision": "${{ needs.build.outputs.image_revision || github.sha }}",
#              "run_name": "${{ env.RUN_NAME }}"
#            }
