import {generateCode} from "@ton-community/tlb-codegen"
import {readFile, writeFile} from "node:fs/promises"

const SOURCE_REVISION = "3d478cbde854be03a18ab2a59f8fc3c565cf7d14"
const schemaUrl = new URL("../src/cell-inspector/block.tlb", import.meta.url)
const outputUrl = new URL("../src/cell-inspector/block.tlb.generated.ts", import.meta.url)
const schema = await readFile(schemaUrl, "utf8")
const generated = generateCode(schema, "typescript")

const header = `// Generated by scripts/generate-block-tlb.ts. Do not edit manually.
// Source: ton-blockchain/ton@${SOURCE_REVISION}/crypto/block/block.tlb
// @ts-nocheck

`

await writeFile(outputUrl, `${header}${generated.trimEnd()}\n`)
