[package]
name = "func-ty"
version = { workspace = true }
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]
test = false
doctest = false

[dependencies]
func-resolver = { path = "../func-resolver" }
tree-sitter = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }

[lints]
workspace = true
