build:
    cargo build --release

build-dev:
    cargo build

fmt-check:
    cargo fmt --all --check

check-deps:
    cargo shear --deny-warnings

clippy:
    cargo clippy --workspace --all-targets --all-features --locked -- -D warnings

check-deny:
    cargo deny check

test:
    true

check: fmt-check check-deps clippy check-deny test
