server {
    listen 3000;
    server_name _;

    location = /ready {
        access_log off;
        return 200;
    }

    location = /health {
        access_log off;
        return 200;
    }

    location = /metrics {
        access_log off;
        return 200;
    }

    location = / {
        default_type text/plain;
        return 200 "faucet.ton.org v2";
    }
}
